### ISSUE TITLE
Probability is greater than 1.0 

### ISSUE THREAD

**Issue by stubbornfox** [utwente-db/DuBio#8]
When calculating the probability for a bdd, I received the prob > 1.

Example:
dictionary:
`b=0:0.830994; b=1:0.157258; b=2:0.011748;`
`c=0:0.998580; c=1:0.000973; c=2:0.000447;`

`Bdd((b=0|(b=1|c=0)))` has prob=1.67254

**Comment by janflokstra** [comment]
Issue is fixed. We completely rewrote the probabilty algorithm. The problem was the multiple values in the low chain of the bdd. When b!=0 and the bdd goes into the 'low' branch the b=1 probability changes from 0.157258 to .930487674 :-)
